### PR TITLE
Fastlane updates

### PR DESCRIPTION
**Pull request by IzzySoft**
…for your F-Droid listing:

* `full_description.txt` (aka "Description") was missing. This is essential.
* German summary (`short_description.txt`) added (nice to have :wink:)
* fixed naming of changelog (must be `<versionCode>.txt`, not `<versionName>.txt`)

### CODE REVIEW

**Comment by qcasey** [comment]
Thank you very much!

**Comment by IzzySoft** [comment]
Anytime! Btw, in case you find it helpful, here's my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) :smiley:

**Comment by qcasey** [comment]
Bookmarked! I'll use this for the next release :smiley:

**Comment by IzzySoft** [comment]
Wonderful! I've already told my updater to look for it :smiley:

Oh, I might have forgotten to tell you about [this link](https://apt.izzysoft.de/fdroid/index/apk/com.quinncasey.paperless_share) – about two hours ago your app popped up in my repo… Speaking about that: shall I keep it there once your app got listed at F-Droid – or remove it again about a week later, as I usually do? In about 80% of the cases I remove it then, on request I can keep it. Just let me know how you want it.

**Comment by qcasey** [comment]
That's excellent - I use your repo on my personal phone and just saw Paperless Share appear on a refresh. Very cool :+1: 

I don't mind either way - whatever you'd like to do. It may be redundant once it's on FDroid but it's your repo. I appreciate you asking - and for all your help.

**Comment by IzzySoft** [comment]
Thanks Quinn – I've put a note to your app's metadata here. Let me list the pros and cons of keeping the app in my repo:

**Pros:**

* faster updates – which would come into play if you have more than 1 or 2 releases per month (updates here within 24h, at F-Droid usually within 7 days unless the build server has a hick-up again).
* cross-updates with Play Store – only relevant if your app is on Play. Users having it from there could easily dump Play and get it from here, as both APKs have your signature. Should you go for "reproducible builds", this would be true for F-Droid as well; but while this point then would be weaker, the previous one would gain weight :smile:

**Cons:**

* on first installation via the F-Droid app, the "average user" might install it from my repo instead of from F-Droid without being aware. Of course only if that "avarage user" had my repo configured – which would mean quite a bit less "average". Switching over to the F-Droid build would then mean uninstall + reinstall (different signature). Would become irrelevant with reproducible builds.

Guess that rawly covers the arguments. With your APKs being much less than 10M each, my keeping 3 of them means a little more than 20M, which doesn't really hurt my "bill". So I'm open to both as well.

Now we've got some weeks to think about :laughing:

**Comment by qcasey** [comment]
Well then it seems like keeping it in your repo may be the best option for now. I didn't know about the cross-updates from Google Play. That's a nice feature I think is great for users.

**Comment by IzzySoft** [comment]
That and the faster updates are the reasons I offer it. Else it would not make that much sense: who's using the F-Droid client usually does not disable the F-Droid repo, so keeping it in both would not really add value.

Just thought I maybe should add those facts to the wiki. Well, looks like [I already did](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) – so it just needed a minor update :smile:

**Comment by qcasey** [comment]
We're glad you do offer it! Cheers mate

**Pull request merged**
